//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace softWrench.sW4.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SWWOBinding", Namespace="http://www.mro.com/mx/wsdl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXMBO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXInterfaceBase))]
    public partial class SWWO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processDocumentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SWWO() {
            this.Url = global::softWrench.sW4.Properties.Settings.Default.softWrench_sW4_WebReference_SWWO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processDocumentCompletedEventHandler processDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void processDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.mro.com/mx/integration")] SWWO1 SWWO) {
            this.Invoke("processDocument", new object[] {
                        SWWO});
        }
        
        /// <remarks/>
        public void processDocumentAsync(SWWO1 SWWO) {
            this.processDocumentAsync(SWWO, null);
        }
        
        /// <remarks/>
        public void processDocumentAsync(SWWO1 SWWO, object userState) {
            if ((this.processDocumentOperationCompleted == null)) {
                this.processDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDocumentOperationCompleted);
            }
            this.InvokeAsync("processDocument", new object[] {
                        SWWO}, this.processDocumentOperationCompleted, userState);
        }
        
        private void OnprocessDocumentOperationCompleted(object arg) {
            if ((this.processDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDocumentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SWWO", Namespace="http://www.mro.com/mx/integration")]
    public partial class SWWO1 : MXNotifyInterface {
        
        private SWWO2SWWO2[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SWWO2", IsNullable=false)]
        public SWWO2SWWO2[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mro.com/mx/integration")]
    public partial class SWWO2SWWO2 {
        
        private SWWO2_WORKORDER wORKORDERField;
        
        /// <remarks/>
        public SWWO2_WORKORDER WORKORDER {
            get {
                return this.wORKORDERField;
            }
            set {
                this.wORKORDERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class SWWO2_WORKORDER : MXMBO {
        
        private MXString wONUMField;
        
        private MXString pARENTField;
        
        private MXDomain sTATUSField;
        
        private MXDateTime sTATUSDATEField;
        
        private MXString wORKTYPEField;
        
        private MXString lEADCRAFTField;
        
        private MXString dESCRIPTIONField;
        
        private MXString lOCATIONField;
        
        private MXString jPNUMField;
        
        private MXDateTime fAILDATEField;
        
        private MXString cHANGEBYField;
        
        private MXDateTime cHANGEDATEField;
        
        private MXDouble eSTDURField;
        
        private MXDouble eSTLABHRSField;
        
        private MXDouble eSTMATCOSTField;
        
        private MXDouble eSTLABCOSTField;
        
        private MXDouble eSTTOOLCOSTField;
        
        private MXString pMNUMField;
        
        private MXDouble aCTLABHRSField;
        
        private MXDouble aCTMATCOSTField;
        
        private MXDouble aCTLABCOSTField;
        
        private MXDouble aCTTOOLCOSTField;
        
        private MXBoolean hASCHILDRENField;
        
        private MXDouble oUTLABCOSTField;
        
        private MXDouble oUTMATCOSTField;
        
        private MXDouble oUTTOOLCOSTField;
        
        private MXBoolean hISTORYFLAGField;
        
        private MXString cONTRACTField;
        
        private MXLong wOPRIORITYField;
        
        private MXDateTime tARGCOMPDATEField;
        
        private MXDateTime tARGSTARTDATEField;
        
        private MXString wOEQ1Field;
        
        private MXString wOEQ2Field;
        
        private MXString wOEQ3Field;
        
        private MXString wOEQ4Field;
        
        private MXDouble wOEQ5Field;
        
        private MXDateTime wOEQ6Field;
        
        private MXDouble wOEQ7Field;
        
        private MXString wOEQ8Field;
        
        private MXString wOEQ9Field;
        
        private MXString wOEQ10Field;
        
        private MXString wOEQ11Field;
        
        private MXDouble wOEQ12Field;
        
        private MXString wO1Field;
        
        private MXString rEPORTEDBYField;
        
        private MXDateTime rEPORTDATEField;
        
        private MXString pHONEField;
        
        private MXString pROBLEMCODEField;
        
        private MXString cALENDARField;
        
        private MXBoolean dOWNTIMEField;
        
        private MXDateTime aCTSTARTField;
        
        private MXDateTime aCTFINISHField;
        
        private MXDateTime sCHEDSTARTField;
        
        private MXDateTime sCHEDFINISHField;
        
        private MXDouble rEMDURField;
        
        private MXString cREWIDField;
        
        private MXString sUPERVISORField;
        
        private MXDateTime wOEQ13Field;
        
        private MXDouble wOEQ14Field;
        
        private MXString wOJP1Field;
        
        private MXString wOJP2Field;
        
        private MXString wOJP3Field;
        
        private MXDouble wOJP4Field;
        
        private MXDateTime wOJP5Field;
        
        private MXString wOL1Field;
        
        private MXString wOL2Field;
        
        private MXDouble wOL3Field;
        
        private MXDateTime wOL4Field;
        
        private MXString wOLABLNKField;
        
        private MXDateTime rESPONDBYField;
        
        private MXLong cALCPRIORITYField;
        
        private MXBoolean cHARGESTOREField;
        
        private MXString fAILURECODEField;
        
        private MXString wOLO1Field;
        
        private MXString wOLO2Field;
        
        private MXString wOLO3Field;
        
        private MXString wOLO4Field;
        
        private MXString wOLO5Field;
        
        private MXDouble wOLO6Field;
        
        private MXDateTime wOLO7Field;
        
        private MXDouble wOLO8Field;
        
        private MXString wOLO9Field;
        
        private MXLong wOLO10Field;
        
        private MXGLAccount gLACCOUNTField;
        
        private MXDouble eSTSERVCOSTField;
        
        private MXDouble aCTSERVCOSTField;
        
        private MXBoolean dISABLEDField;
        
        private MXDouble eSTATAPPRLABHRSField;
        
        private MXDouble eSTATAPPRLABCOSTField;
        
        private MXDouble eSTATAPPRMATCOSTField;
        
        private MXDouble eSTATAPPRTOOLCOSTField;
        
        private MXDouble eSTATAPPRSERVCOSTField;
        
        private MXLong wOSEQUENCEField;
        
        private MXBoolean hASFOLLOWUPWORKField;
        
        private MXString wORTS1Field;
        
        private MXString wORTS2Field;
        
        private MXString wORTS3Field;
        
        private MXDateTime wORTS4Field;
        
        private MXDouble wORTS5Field;
        
        private MXString sOURCESYSIDField;
        
        private MXString oWNERSYSIDField;
        
        private MXDateTime pMDUEDATEField;
        
        private MXDateTime pMEXTDATEField;
        
        private MXDateTime pMNEXTDUEDATEField;
        
        private MXString wORKLOCATIONField;
        
        private MXBoolean wO20Field;
        
        private MXString eXTERNALREFIDField;
        
        private MXString aPISEQField;
        
        private MXString sENDERSYSIDField;
        
        private MXString fINCNTRLIDField;
        
        private MXString gENERATEDFORPOField;
        
        private MXLong gENFORPOLINEIDField;
        
        private MXString oRGIDField;
        
        private MXString sITEIDField;
        
        private MXLong tASKIDField;
        
        private MXString iNSPECTORField;
        
        private MXDouble mEASUREMENTVALUEField;
        
        private MXDateTime mEASUREDATEField;
        
        private MXString oBSERVATIONField;
        
        private MXString pOINTNUMField;
        
        private MXString wOJO1Field;
        
        private MXString wOJO2Field;
        
        private MXString wOJO3Field;
        
        private MXDouble wOJO4Field;
        
        private MXString wOJO5Field;
        
        private MXString wOJO6Field;
        
        private MXString wOJO7Field;
        
        private MXString wOJO8Field;
        
        private MXBoolean iSTASKField;
        
        private MXLong aSSETLOCPRIORITYField;
        
        private MXString aSSETNUMField;
        
        private MXString bACKOUTPLANField;
        
        private MXString cLASSSTRUCTUREIDField;
        
        private MXString cOMMODITYField;
        
        private MXString cOMMODITYGROUPField;
        
        private MXString eNVIRONMENTField;
        
        private MXBoolean iNTERRUPTIBLEField;
        
        private MXString jUSTIFYPRIORITYField;
        
        private MXString lEADField;
        
        private MXString mOVETOBINNUMField;
        
        private MXString mOVETOLOCField;
        
        private MXString mOVETOPARENTField;
        
        private MXString oNBEHALFOFField;
        
        private MXString oRIGRECORDCLASSField;
        
        private MXString oRIGRECORDIDField;
        
        private MXString oWNERField;
        
        private MXString oWNERGROUPField;
        
        private MXBoolean pARENTCHGSSTATUSField;
        
        private MXBoolean pERFORMMOVETOField;
        
        private MXString pERSONGROUPField;
        
        private MXString rEASONFORCHANGEField;
        
        private MXString rISKField;
        
        private MXString vENDORField;
        
        private MXString vERIFICATIONField;
        
        private MXString wHOMISCHANGEFORField;
        
        private MXBoolean wOACCEPTSCHARGESField;
        
        private MXDomain wOCLASSField;
        
        private MXString wOGROUPField;
        
        private MXLong wORKORDERIDField;
        
        private MXString bKPCONTRACTField;
        
        private MXDouble aCTTOTCOSTField;
        
        private MXDouble eSTATAPPRTOTCOSTField;
        
        private MXDouble oUTTOTCOSTField;
        
        private MXString sWTESTField;
        
        /// <remarks/>
        public MXString WONUM {
            get {
                return this.wONUMField;
            }
            set {
                this.wONUMField = value;
            }
        }
        
        /// <remarks/>
        public MXString PARENT {
            get {
                return this.pARENTField;
            }
            set {
                this.pARENTField = value;
            }
        }
        
        /// <remarks/>
        public MXDomain STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public MXDateTime STATUSDATE {
            get {
                return this.sTATUSDATEField;
            }
            set {
                this.sTATUSDATEField = value;
            }
        }
        
        /// <remarks/>
        public MXString WORKTYPE {
            get {
                return this.wORKTYPEField;
            }
            set {
                this.wORKTYPEField = value;
            }
        }
        
        /// <remarks/>
        public MXString LEADCRAFT {
            get {
                return this.lEADCRAFTField;
            }
            set {
                this.lEADCRAFTField = value;
            }
        }
        
        /// <remarks/>
        public MXString DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public MXString LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
            }
        }
        
        /// <remarks/>
        public MXString JPNUM {
            get {
                return this.jPNUMField;
            }
            set {
                this.jPNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime FAILDATE {
            get {
                return this.fAILDATEField;
            }
            set {
                this.fAILDATEField = value;
            }
        }
        
        /// <remarks/>
        public MXString CHANGEBY {
            get {
                return this.cHANGEBYField;
            }
            set {
                this.cHANGEBYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime CHANGEDATE {
            get {
                return this.cHANGEDATEField;
            }
            set {
                this.cHANGEDATEField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTDUR {
            get {
                return this.eSTDURField;
            }
            set {
                this.eSTDURField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTLABHRS {
            get {
                return this.eSTLABHRSField;
            }
            set {
                this.eSTLABHRSField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTMATCOST {
            get {
                return this.eSTMATCOSTField;
            }
            set {
                this.eSTMATCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTLABCOST {
            get {
                return this.eSTLABCOSTField;
            }
            set {
                this.eSTLABCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTTOOLCOST {
            get {
                return this.eSTTOOLCOSTField;
            }
            set {
                this.eSTTOOLCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXString PMNUM {
            get {
                return this.pMNUMField;
            }
            set {
                this.pMNUMField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ACTLABHRS {
            get {
                return this.aCTLABHRSField;
            }
            set {
                this.aCTLABHRSField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ACTMATCOST {
            get {
                return this.aCTMATCOSTField;
            }
            set {
                this.aCTMATCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ACTLABCOST {
            get {
                return this.aCTLABCOSTField;
            }
            set {
                this.aCTLABCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ACTTOOLCOST {
            get {
                return this.aCTTOOLCOSTField;
            }
            set {
                this.aCTTOOLCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean HASCHILDREN {
            get {
                return this.hASCHILDRENField;
            }
            set {
                this.hASCHILDRENField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble OUTLABCOST {
            get {
                return this.oUTLABCOSTField;
            }
            set {
                this.oUTLABCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble OUTMATCOST {
            get {
                return this.oUTMATCOSTField;
            }
            set {
                this.oUTMATCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble OUTTOOLCOST {
            get {
                return this.oUTTOOLCOSTField;
            }
            set {
                this.oUTTOOLCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean HISTORYFLAG {
            get {
                return this.hISTORYFLAGField;
            }
            set {
                this.hISTORYFLAGField = value;
            }
        }
        
        /// <remarks/>
        public MXString CONTRACT {
            get {
                return this.cONTRACTField;
            }
            set {
                this.cONTRACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLong WOPRIORITY {
            get {
                return this.wOPRIORITYField;
            }
            set {
                this.wOPRIORITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime TARGCOMPDATE {
            get {
                return this.tARGCOMPDATEField;
            }
            set {
                this.tARGCOMPDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime TARGSTARTDATE {
            get {
                return this.tARGSTARTDATEField;
            }
            set {
                this.tARGSTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ1 {
            get {
                return this.wOEQ1Field;
            }
            set {
                this.wOEQ1Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ2 {
            get {
                return this.wOEQ2Field;
            }
            set {
                this.wOEQ2Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ3 {
            get {
                return this.wOEQ3Field;
            }
            set {
                this.wOEQ3Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ4 {
            get {
                return this.wOEQ4Field;
            }
            set {
                this.wOEQ4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOEQ5 {
            get {
                return this.wOEQ5Field;
            }
            set {
                this.wOEQ5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime WOEQ6 {
            get {
                return this.wOEQ6Field;
            }
            set {
                this.wOEQ6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOEQ7 {
            get {
                return this.wOEQ7Field;
            }
            set {
                this.wOEQ7Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ8 {
            get {
                return this.wOEQ8Field;
            }
            set {
                this.wOEQ8Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ9 {
            get {
                return this.wOEQ9Field;
            }
            set {
                this.wOEQ9Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ10 {
            get {
                return this.wOEQ10Field;
            }
            set {
                this.wOEQ10Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOEQ11 {
            get {
                return this.wOEQ11Field;
            }
            set {
                this.wOEQ11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOEQ12 {
            get {
                return this.wOEQ12Field;
            }
            set {
                this.wOEQ12Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WO1 {
            get {
                return this.wO1Field;
            }
            set {
                this.wO1Field = value;
            }
        }
        
        /// <remarks/>
        public MXString REPORTEDBY {
            get {
                return this.rEPORTEDBYField;
            }
            set {
                this.rEPORTEDBYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime REPORTDATE {
            get {
                return this.rEPORTDATEField;
            }
            set {
                this.rEPORTDATEField = value;
            }
        }
        
        /// <remarks/>
        public MXString PHONE {
            get {
                return this.pHONEField;
            }
            set {
                this.pHONEField = value;
            }
        }
        
        /// <remarks/>
        public MXString PROBLEMCODE {
            get {
                return this.pROBLEMCODEField;
            }
            set {
                this.pROBLEMCODEField = value;
            }
        }
        
        /// <remarks/>
        public MXString CALENDAR {
            get {
                return this.cALENDARField;
            }
            set {
                this.cALENDARField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean DOWNTIME {
            get {
                return this.dOWNTIMEField;
            }
            set {
                this.dOWNTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime ACTSTART {
            get {
                return this.aCTSTARTField;
            }
            set {
                this.aCTSTARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime ACTFINISH {
            get {
                return this.aCTFINISHField;
            }
            set {
                this.aCTFINISHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime SCHEDSTART {
            get {
                return this.sCHEDSTARTField;
            }
            set {
                this.sCHEDSTARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime SCHEDFINISH {
            get {
                return this.sCHEDFINISHField;
            }
            set {
                this.sCHEDFINISHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble REMDUR {
            get {
                return this.rEMDURField;
            }
            set {
                this.rEMDURField = value;
            }
        }
        
        /// <remarks/>
        public MXString CREWID {
            get {
                return this.cREWIDField;
            }
            set {
                this.cREWIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString SUPERVISOR {
            get {
                return this.sUPERVISORField;
            }
            set {
                this.sUPERVISORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime WOEQ13 {
            get {
                return this.wOEQ13Field;
            }
            set {
                this.wOEQ13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOEQ14 {
            get {
                return this.wOEQ14Field;
            }
            set {
                this.wOEQ14Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJP1 {
            get {
                return this.wOJP1Field;
            }
            set {
                this.wOJP1Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJP2 {
            get {
                return this.wOJP2Field;
            }
            set {
                this.wOJP2Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJP3 {
            get {
                return this.wOJP3Field;
            }
            set {
                this.wOJP3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOJP4 {
            get {
                return this.wOJP4Field;
            }
            set {
                this.wOJP4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime WOJP5 {
            get {
                return this.wOJP5Field;
            }
            set {
                this.wOJP5Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOL1 {
            get {
                return this.wOL1Field;
            }
            set {
                this.wOL1Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOL2 {
            get {
                return this.wOL2Field;
            }
            set {
                this.wOL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOL3 {
            get {
                return this.wOL3Field;
            }
            set {
                this.wOL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime WOL4 {
            get {
                return this.wOL4Field;
            }
            set {
                this.wOL4Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOLABLNK {
            get {
                return this.wOLABLNKField;
            }
            set {
                this.wOLABLNKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime RESPONDBY {
            get {
                return this.rESPONDBYField;
            }
            set {
                this.rESPONDBYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLong CALCPRIORITY {
            get {
                return this.cALCPRIORITYField;
            }
            set {
                this.cALCPRIORITYField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean CHARGESTORE {
            get {
                return this.cHARGESTOREField;
            }
            set {
                this.cHARGESTOREField = value;
            }
        }
        
        /// <remarks/>
        public MXString FAILURECODE {
            get {
                return this.fAILURECODEField;
            }
            set {
                this.fAILURECODEField = value;
            }
        }
        
        /// <remarks/>
        public MXString WOLO1 {
            get {
                return this.wOLO1Field;
            }
            set {
                this.wOLO1Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOLO2 {
            get {
                return this.wOLO2Field;
            }
            set {
                this.wOLO2Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOLO3 {
            get {
                return this.wOLO3Field;
            }
            set {
                this.wOLO3Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOLO4 {
            get {
                return this.wOLO4Field;
            }
            set {
                this.wOLO4Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOLO5 {
            get {
                return this.wOLO5Field;
            }
            set {
                this.wOLO5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOLO6 {
            get {
                return this.wOLO6Field;
            }
            set {
                this.wOLO6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime WOLO7 {
            get {
                return this.wOLO7Field;
            }
            set {
                this.wOLO7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOLO8 {
            get {
                return this.wOLO8Field;
            }
            set {
                this.wOLO8Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOLO9 {
            get {
                return this.wOLO9Field;
            }
            set {
                this.wOLO9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLong WOLO10 {
            get {
                return this.wOLO10Field;
            }
            set {
                this.wOLO10Field = value;
            }
        }
        
        /// <remarks/>
        public MXGLAccount GLACCOUNT {
            get {
                return this.gLACCOUNTField;
            }
            set {
                this.gLACCOUNTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTSERVCOST {
            get {
                return this.eSTSERVCOSTField;
            }
            set {
                this.eSTSERVCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ACTSERVCOST {
            get {
                return this.aCTSERVCOSTField;
            }
            set {
                this.aCTSERVCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean DISABLED {
            get {
                return this.dISABLEDField;
            }
            set {
                this.dISABLEDField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTATAPPRLABHRS {
            get {
                return this.eSTATAPPRLABHRSField;
            }
            set {
                this.eSTATAPPRLABHRSField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTATAPPRLABCOST {
            get {
                return this.eSTATAPPRLABCOSTField;
            }
            set {
                this.eSTATAPPRLABCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTATAPPRMATCOST {
            get {
                return this.eSTATAPPRMATCOSTField;
            }
            set {
                this.eSTATAPPRMATCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTATAPPRTOOLCOST {
            get {
                return this.eSTATAPPRTOOLCOSTField;
            }
            set {
                this.eSTATAPPRTOOLCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXDouble ESTATAPPRSERVCOST {
            get {
                return this.eSTATAPPRSERVCOSTField;
            }
            set {
                this.eSTATAPPRSERVCOSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLong WOSEQUENCE {
            get {
                return this.wOSEQUENCEField;
            }
            set {
                this.wOSEQUENCEField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean HASFOLLOWUPWORK {
            get {
                return this.hASFOLLOWUPWORKField;
            }
            set {
                this.hASFOLLOWUPWORKField = value;
            }
        }
        
        /// <remarks/>
        public MXString WORTS1 {
            get {
                return this.wORTS1Field;
            }
            set {
                this.wORTS1Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WORTS2 {
            get {
                return this.wORTS2Field;
            }
            set {
                this.wORTS2Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WORTS3 {
            get {
                return this.wORTS3Field;
            }
            set {
                this.wORTS3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime WORTS4 {
            get {
                return this.wORTS4Field;
            }
            set {
                this.wORTS4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WORTS5 {
            get {
                return this.wORTS5Field;
            }
            set {
                this.wORTS5Field = value;
            }
        }
        
        /// <remarks/>
        public MXString SOURCESYSID {
            get {
                return this.sOURCESYSIDField;
            }
            set {
                this.sOURCESYSIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString OWNERSYSID {
            get {
                return this.oWNERSYSIDField;
            }
            set {
                this.oWNERSYSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime PMDUEDATE {
            get {
                return this.pMDUEDATEField;
            }
            set {
                this.pMDUEDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime PMEXTDATE {
            get {
                return this.pMEXTDATEField;
            }
            set {
                this.pMEXTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime PMNEXTDUEDATE {
            get {
                return this.pMNEXTDUEDATEField;
            }
            set {
                this.pMNEXTDUEDATEField = value;
            }
        }
        
        /// <remarks/>
        public MXString WORKLOCATION {
            get {
                return this.wORKLOCATIONField;
            }
            set {
                this.wORKLOCATIONField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean WO20 {
            get {
                return this.wO20Field;
            }
            set {
                this.wO20Field = value;
            }
        }
        
        /// <remarks/>
        public MXString EXTERNALREFID {
            get {
                return this.eXTERNALREFIDField;
            }
            set {
                this.eXTERNALREFIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString APISEQ {
            get {
                return this.aPISEQField;
            }
            set {
                this.aPISEQField = value;
            }
        }
        
        /// <remarks/>
        public MXString SENDERSYSID {
            get {
                return this.sENDERSYSIDField;
            }
            set {
                this.sENDERSYSIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString FINCNTRLID {
            get {
                return this.fINCNTRLIDField;
            }
            set {
                this.fINCNTRLIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString GENERATEDFORPO {
            get {
                return this.gENERATEDFORPOField;
            }
            set {
                this.gENERATEDFORPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLong GENFORPOLINEID {
            get {
                return this.gENFORPOLINEIDField;
            }
            set {
                this.gENFORPOLINEIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString ORGID {
            get {
                return this.oRGIDField;
            }
            set {
                this.oRGIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLong TASKID {
            get {
                return this.tASKIDField;
            }
            set {
                this.tASKIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString INSPECTOR {
            get {
                return this.iNSPECTORField;
            }
            set {
                this.iNSPECTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble MEASUREMENTVALUE {
            get {
                return this.mEASUREMENTVALUEField;
            }
            set {
                this.mEASUREMENTVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDateTime MEASUREDATE {
            get {
                return this.mEASUREDATEField;
            }
            set {
                this.mEASUREDATEField = value;
            }
        }
        
        /// <remarks/>
        public MXString OBSERVATION {
            get {
                return this.oBSERVATIONField;
            }
            set {
                this.oBSERVATIONField = value;
            }
        }
        
        /// <remarks/>
        public MXString POINTNUM {
            get {
                return this.pOINTNUMField;
            }
            set {
                this.pOINTNUMField = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJO1 {
            get {
                return this.wOJO1Field;
            }
            set {
                this.wOJO1Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJO2 {
            get {
                return this.wOJO2Field;
            }
            set {
                this.wOJO2Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJO3 {
            get {
                return this.wOJO3Field;
            }
            set {
                this.wOJO3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble WOJO4 {
            get {
                return this.wOJO4Field;
            }
            set {
                this.wOJO4Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJO5 {
            get {
                return this.wOJO5Field;
            }
            set {
                this.wOJO5Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJO6 {
            get {
                return this.wOJO6Field;
            }
            set {
                this.wOJO6Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJO7 {
            get {
                return this.wOJO7Field;
            }
            set {
                this.wOJO7Field = value;
            }
        }
        
        /// <remarks/>
        public MXString WOJO8 {
            get {
                return this.wOJO8Field;
            }
            set {
                this.wOJO8Field = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean ISTASK {
            get {
                return this.iSTASKField;
            }
            set {
                this.iSTASKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXLong ASSETLOCPRIORITY {
            get {
                return this.aSSETLOCPRIORITYField;
            }
            set {
                this.aSSETLOCPRIORITYField = value;
            }
        }
        
        /// <remarks/>
        public MXString ASSETNUM {
            get {
                return this.aSSETNUMField;
            }
            set {
                this.aSSETNUMField = value;
            }
        }
        
        /// <remarks/>
        public MXString BACKOUTPLAN {
            get {
                return this.bACKOUTPLANField;
            }
            set {
                this.bACKOUTPLANField = value;
            }
        }
        
        /// <remarks/>
        public MXString CLASSSTRUCTUREID {
            get {
                return this.cLASSSTRUCTUREIDField;
            }
            set {
                this.cLASSSTRUCTUREIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString COMMODITY {
            get {
                return this.cOMMODITYField;
            }
            set {
                this.cOMMODITYField = value;
            }
        }
        
        /// <remarks/>
        public MXString COMMODITYGROUP {
            get {
                return this.cOMMODITYGROUPField;
            }
            set {
                this.cOMMODITYGROUPField = value;
            }
        }
        
        /// <remarks/>
        public MXString ENVIRONMENT {
            get {
                return this.eNVIRONMENTField;
            }
            set {
                this.eNVIRONMENTField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean INTERRUPTIBLE {
            get {
                return this.iNTERRUPTIBLEField;
            }
            set {
                this.iNTERRUPTIBLEField = value;
            }
        }
        
        /// <remarks/>
        public MXString JUSTIFYPRIORITY {
            get {
                return this.jUSTIFYPRIORITYField;
            }
            set {
                this.jUSTIFYPRIORITYField = value;
            }
        }
        
        /// <remarks/>
        public MXString LEAD {
            get {
                return this.lEADField;
            }
            set {
                this.lEADField = value;
            }
        }
        
        /// <remarks/>
        public MXString MOVETOBINNUM {
            get {
                return this.mOVETOBINNUMField;
            }
            set {
                this.mOVETOBINNUMField = value;
            }
        }
        
        /// <remarks/>
        public MXString MOVETOLOC {
            get {
                return this.mOVETOLOCField;
            }
            set {
                this.mOVETOLOCField = value;
            }
        }
        
        /// <remarks/>
        public MXString MOVETOPARENT {
            get {
                return this.mOVETOPARENTField;
            }
            set {
                this.mOVETOPARENTField = value;
            }
        }
        
        /// <remarks/>
        public MXString ONBEHALFOF {
            get {
                return this.oNBEHALFOFField;
            }
            set {
                this.oNBEHALFOFField = value;
            }
        }
        
        /// <remarks/>
        public MXString ORIGRECORDCLASS {
            get {
                return this.oRIGRECORDCLASSField;
            }
            set {
                this.oRIGRECORDCLASSField = value;
            }
        }
        
        /// <remarks/>
        public MXString ORIGRECORDID {
            get {
                return this.oRIGRECORDIDField;
            }
            set {
                this.oRIGRECORDIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString OWNER {
            get {
                return this.oWNERField;
            }
            set {
                this.oWNERField = value;
            }
        }
        
        /// <remarks/>
        public MXString OWNERGROUP {
            get {
                return this.oWNERGROUPField;
            }
            set {
                this.oWNERGROUPField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean PARENTCHGSSTATUS {
            get {
                return this.pARENTCHGSSTATUSField;
            }
            set {
                this.pARENTCHGSSTATUSField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean PERFORMMOVETO {
            get {
                return this.pERFORMMOVETOField;
            }
            set {
                this.pERFORMMOVETOField = value;
            }
        }
        
        /// <remarks/>
        public MXString PERSONGROUP {
            get {
                return this.pERSONGROUPField;
            }
            set {
                this.pERSONGROUPField = value;
            }
        }
        
        /// <remarks/>
        public MXString REASONFORCHANGE {
            get {
                return this.rEASONFORCHANGEField;
            }
            set {
                this.rEASONFORCHANGEField = value;
            }
        }
        
        /// <remarks/>
        public MXString RISK {
            get {
                return this.rISKField;
            }
            set {
                this.rISKField = value;
            }
        }
        
        /// <remarks/>
        public MXString VENDOR {
            get {
                return this.vENDORField;
            }
            set {
                this.vENDORField = value;
            }
        }
        
        /// <remarks/>
        public MXString VERIFICATION {
            get {
                return this.vERIFICATIONField;
            }
            set {
                this.vERIFICATIONField = value;
            }
        }
        
        /// <remarks/>
        public MXString WHOMISCHANGEFOR {
            get {
                return this.wHOMISCHANGEFORField;
            }
            set {
                this.wHOMISCHANGEFORField = value;
            }
        }
        
        /// <remarks/>
        public MXBoolean WOACCEPTSCHARGES {
            get {
                return this.wOACCEPTSCHARGESField;
            }
            set {
                this.wOACCEPTSCHARGESField = value;
            }
        }
        
        /// <remarks/>
        public MXDomain WOCLASS {
            get {
                return this.wOCLASSField;
            }
            set {
                this.wOCLASSField = value;
            }
        }
        
        /// <remarks/>
        public MXString WOGROUP {
            get {
                return this.wOGROUPField;
            }
            set {
                this.wOGROUPField = value;
            }
        }
        
        /// <remarks/>
        public MXLong WORKORDERID {
            get {
                return this.wORKORDERIDField;
            }
            set {
                this.wORKORDERIDField = value;
            }
        }
        
        /// <remarks/>
        public MXString BKPCONTRACT {
            get {
                return this.bKPCONTRACTField;
            }
            set {
                this.bKPCONTRACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble ACTTOTCOST {
            get {
                return this.aCTTOTCOSTField;
            }
            set {
                this.aCTTOTCOSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble ESTATAPPRTOTCOST {
            get {
                return this.eSTATAPPRTOTCOSTField;
            }
            set {
                this.eSTATAPPRTOTCOSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MXDouble OUTTOTCOST {
            get {
                return this.oUTTOTCOSTField;
            }
            set {
                this.oUTTOTCOSTField = value;
            }
        }
        
        /// <remarks/>
        public MXString SWTEST {
            get {
                return this.sWTESTField;
            }
            set {
                this.sWTESTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXDomain))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXString {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public enum QueryOperator {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("=")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("!=")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<=")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">=")]
        Item5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXGLComponent {
        
        private int glorderField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int glorder {
            get {
                return this.glorderField;
            }
            set {
                this.glorderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXGLAccount {
        
        private string vALUEField;
        
        private MXGLComponent[] gLCOMPField;
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        /// <remarks/>
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GLCOMP")]
        public MXGLComponent[] GLCOMP {
            get {
                return this.gLCOMPField;
            }
            set {
                this.gLCOMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXLong {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXBoolean {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXDouble {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXDateTime {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SWWO2_WORKORDER))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public abstract partial class MXMBO {
        
        private ProcessingAction actionField;
        
        private bool actionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public enum ProcessingAction {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Change,
        
        /// <remarks/>
        Replace,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        AddChange,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXResponseCriteria {
        
        private string[] responseContentField;
        
        private string expressionLanguageField;
        
        public MXResponseCriteria() {
            this.expressionLanguageField = "XPath";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseContent")]
        public string[] ResponseContent {
            get {
                return this.responseContentField;
            }
            set {
                this.responseContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXSender {
        
        private string typeField;
        
        private string majorversionField;
        
        private string minorversionField;
        
        private string buildField;
        
        private string dbbuildField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string majorversion {
            get {
                return this.majorversionField;
            }
            set {
                this.majorversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minorversion {
            get {
                return this.minorversionField;
            }
            set {
                this.minorversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dbbuild {
            get {
                return this.dbbuildField;
            }
            set {
                this.dbbuildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXResponseHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXQueryHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXNotifyHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXHeader {
        
        private MXSender senderIDField;
        
        private System.DateTime creationDateTimeField;
        
        private string recipientIDField;
        
        private string messageIDField;
        
        /// <remarks/>
        public MXSender SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationDateTime {
            get {
                return this.creationDateTimeField;
            }
            set {
                this.creationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientID {
            get {
                return this.recipientIDField;
            }
            set {
                this.recipientIDField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXResponseHeader : MXHeader {
        
        private string operationField;
        
        private bool eventField;
        
        private bool eventFieldSpecified;
        
        private string rsStartField;
        
        private string rsCountField;
        
        private string rsTotalField;
        
        public MXResponseHeader() {
            this.operationField = "Response";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventSpecified {
            get {
                return this.eventFieldSpecified;
            }
            set {
                this.eventFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsStart {
            get {
                return this.rsStartField;
            }
            set {
                this.rsStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsCount {
            get {
                return this.rsCountField;
            }
            set {
                this.rsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsTotal {
            get {
                return this.rsTotalField;
            }
            set {
                this.rsTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXQueryHeader : MXHeader {
        
        private MXResponseCriteria responseCriteriaField;
        
        private string operationField;
        
        private bool uniqueResultField;
        
        private bool uniqueResultFieldSpecified;
        
        private string maxItemsField;
        
        private string rsStartField;
        
        public MXQueryHeader() {
            this.operationField = "Query";
        }
        
        /// <remarks/>
        public MXResponseCriteria ResponseCriteria {
            get {
                return this.responseCriteriaField;
            }
            set {
                this.responseCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool uniqueResult {
            get {
                return this.uniqueResultField;
            }
            set {
                this.uniqueResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uniqueResultSpecified {
            get {
                return this.uniqueResultFieldSpecified;
            }
            set {
                this.uniqueResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string maxItems {
            get {
                return this.maxItemsField;
            }
            set {
                this.maxItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsStart {
            get {
                return this.rsStartField;
            }
            set {
                this.rsStartField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXNotifyHeader : MXHeader {
        
        private string operationField;
        
        private bool eventField;
        
        private bool eventFieldSpecified;
        
        public MXNotifyHeader() {
            this.operationField = "Notify";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventSpecified {
            get {
                return this.eventFieldSpecified;
            }
            set {
                this.eventFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXResponseInterface))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXQueryInterface))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXNotifyInterface))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SWWO1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public abstract partial class MXInterfaceBase {
        
        private string languageField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXResponseInterface : MXInterfaceBase {
        
        private MXResponseHeader headerField;
        
        /// <remarks/>
        public MXResponseHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXQueryInterface : MXInterfaceBase {
        
        private MXQueryHeader headerField;
        
        /// <remarks/>
        public MXQueryHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SWWO1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXNotifyInterface : MXInterfaceBase {
        
        private MXNotifyHeader headerField;
        
        /// <remarks/>
        public MXNotifyHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXDomain : MXString {
        
        private string maxvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxvalue {
            get {
                return this.maxvalueField;
            }
            set {
                this.maxvalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void processDocumentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591