using System.Diagnostics;
using System.Globalization;
using log4net;
using softWrench.sW4.Data.Offline;
using softwrench.sW4.Shared2.Metadata.Applications.Schema;
using softwrench.sW4.Shared2.Metadata.Applications.Schema.Interfaces;
using softwrench.sW4.Shared2.Metadata.Applications.UI;
using softWrench.sW4.Util;
using System.Collections.Generic;
using softwrench.sw4.Shared2.Metadata.Applications.Schema;

namespace softWrench.sW4.Metadata.Applications.Schema {
    class ApplicationSchemaLazyFkHandler {

        private static readonly ILog Log = LogManager.GetLogger(typeof(ApplicationSchemaLazyFkHandler));

        public static ApplicationSchemaDefinition.LazyFkResolverDelegate SyncSchemaLazyFkResolverDelegate =
            delegate (ApplicationSchemaDefinition definition) {
                if (!MetadataProvider.FinishedParsing) {
                    return null;
                }
                Log.DebugFormat("resolving lazy sync fields for application {0}", definition.ApplicationName);
                var app = MetadataProvider.Application(definition.ApplicationName);
                var schemas = app.MobileSchemas();
                var resultSet = new HashSet<IApplicationDisplayable>();
                foreach (var schema in schemas) {
                    if (Equals(schema.GetSchemaKey(), definition.GetSchemaKey()) || schema.IsWebPlatform()) {
                        continue;
                    }
                    var fields = schema.Displayables;
                    foreach (var applicationFieldDefinition in fields) {
                        resultSet.Add(applicationFieldDefinition);
                    }
                    resultSet.Add(new ApplicationFieldDefinition(definition.ApplicationName, RowStampUtil.RowstampColumnName, RowStampUtil.RowstampColumnName) {
                        Renderer = new FieldRenderer()
                    });
                }
                return new List<IApplicationDisplayable>(resultSet);
            };


        public static ApplicationSchemaDefinition.LazySchemaFilterResolver LazyFilterResolver =
            delegate (ApplicationSchemaDefinition definition) {

//                if (!MetadataProvider.FinishedParsing) {
//                    return null;
//                }

                return SchemaFilterBuilder.BuildSchemaFilters(definition);
            };


        public static ApplicationSchemaDefinition.LazyFkResolverDelegate LazyFkResolverDelegate = delegate (ApplicationSchemaDefinition definition) {
            var watch = Stopwatch.StartNew();
            if (!MetadataProvider.FinishedParsing) {
                return null;
            }
            if (definition.Stereotype != SchemaStereotype.List &&
                definition.Stereotype != SchemaStereotype.CompositionList) {
                //blank list in order to consider it done
                return new List<IApplicationDisplayable>();
            }
            var resultList = new List<IApplicationDisplayable>();
            resultList.AddRange(DirectFKsFields(definition));
            resultList.AddRange(InverseFKsFields(definition));
            Log.DebugFormat("finished LazyFkResolverDelegate took {0} ", watch.ElapsedMilliseconds.ToString(CultureInfo.InvariantCulture));
            return resultList;
        };

        private static IEnumerable<IApplicationAttributeDisplayable> InverseFKsFields(ApplicationSchemaDefinition thisSchema) {
            var resultList = new List<IApplicationAttributeDisplayable>();
            var applications = MetadataProvider.Applications();

            if (MetadataProvider.InternalCache == null) {
                MetadataProvider.InternalCache = new MetadataProviderInternalCache();
            }

            var cache = MetadataProvider.InternalCache;

            var relationshipName = EntityUtil.GetRelationshipName(thisSchema.ApplicationName);

            if (!cache.RelationshipsByNameCache.ContainsKey(relationshipName)) {
                return resultList;
            }

            var relationships = MetadataProvider.InternalCache.RelationshipsByNameCache[relationshipName];

            foreach (var association in relationships) {
                var entityAssociation = association.EntityAssociation;
                foreach (var attribute in entityAssociation.Attributes) {
                    if (attribute.To != null) {
                        var applicationFieldDefinition = ApplicationFieldDefinition.HiddenInstance(thisSchema.ApplicationName, attribute.To);
                        applicationFieldDefinition.AutoGenerated = true;
                        resultList.Add(applicationFieldDefinition);
                    }
                }
            }


            return resultList;
        }

        private static IEnumerable<IApplicationAttributeDisplayable> DirectFKsFields(ApplicationSchemaDefinition schema) {
            return new List<IApplicationAttributeDisplayable>();
        }



    }
}
