//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace softWrench.sW4.mea_swWorkorderStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mro.com/mx/wsdl", ConfigurationName="mea_swWorkorderStatus.SWWOSTATUSPortType")]
    public interface SWWOSTATUSPortType {
        
        // CODEGEN: Generating message contract since the operation processDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MXMBO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MXHeader))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MXInterfaceBase))]
        softWrench.sW4.mea_swWorkorderStatus.processDocumentResponse processDocument(softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<softWrench.sW4.mea_swWorkorderStatus.processDocumentResponse> processDocumentAsync(softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class SWWOSTATUS : MXNotifyInterface {
        
        private SWWOSTATUS_OBJ2SWWOSTATUS_OBJ2[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SWWOSTATUS_OBJ2", IsNullable=false)]
        public SWWOSTATUS_OBJ2SWWOSTATUS_OBJ2[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mro.com/mx/integration")]
    public partial class SWWOSTATUS_OBJ2SWWOSTATUS_OBJ2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SWWOSTATUS_OBJ2_WOSTATUS wOSTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SWWOSTATUS_OBJ2_WOSTATUS WOSTATUS {
            get {
                return this.wOSTATUSField;
            }
            set {
                this.wOSTATUSField = value;
                this.RaisePropertyChanged("WOSTATUS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class SWWOSTATUS_OBJ2_WOSTATUS : MXMBO {
        
        private MXString wONUMField;
        
        private MXString sTATUSField;
        
        private MXDateTime cHANGEDATEField;
        
        private MXString cHANGEBYField;
        
        private MXString mEMOField;
        
        private MXGLAccount gLACCOUNTField;
        
        private MXString fINCNTRLIDField;
        
        private MXString oRGIDField;
        
        private MXString sITEIDField;
        
        private MXLong wOSTATUSIDField;
        
        private MXString pARENTField;
        
        private MXString wOAPPROVERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MXString WONUM {
            get {
                return this.wONUMField;
            }
            set {
                this.wONUMField = value;
                this.RaisePropertyChanged("WONUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MXString STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MXDateTime CHANGEDATE {
            get {
                return this.cHANGEDATEField;
            }
            set {
                this.cHANGEDATEField = value;
                this.RaisePropertyChanged("CHANGEDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MXString CHANGEBY {
            get {
                return this.cHANGEBYField;
            }
            set {
                this.cHANGEBYField = value;
                this.RaisePropertyChanged("CHANGEBY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MXString MEMO {
            get {
                return this.mEMOField;
            }
            set {
                this.mEMOField = value;
                this.RaisePropertyChanged("MEMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public MXGLAccount GLACCOUNT {
            get {
                return this.gLACCOUNTField;
            }
            set {
                this.gLACCOUNTField = value;
                this.RaisePropertyChanged("GLACCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public MXString FINCNTRLID {
            get {
                return this.fINCNTRLIDField;
            }
            set {
                this.fINCNTRLIDField = value;
                this.RaisePropertyChanged("FINCNTRLID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public MXString ORGID {
            get {
                return this.oRGIDField;
            }
            set {
                this.oRGIDField = value;
                this.RaisePropertyChanged("ORGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public MXString SITEID {
            get {
                return this.sITEIDField;
            }
            set {
                this.sITEIDField = value;
                this.RaisePropertyChanged("SITEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public MXLong WOSTATUSID {
            get {
                return this.wOSTATUSIDField;
            }
            set {
                this.wOSTATUSIDField = value;
                this.RaisePropertyChanged("WOSTATUSID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public MXString PARENT {
            get {
                return this.pARENTField;
            }
            set {
                this.pARENTField = value;
                this.RaisePropertyChanged("PARENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public MXString WOAPPROVER {
            get {
                return this.wOAPPROVERField;
            }
            set {
                this.wOAPPROVERField = value;
                this.RaisePropertyChanged("WOAPPROVER");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXDomain))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
                this.RaisePropertyChanged("changed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
                this.RaisePropertyChanged("changedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
                this.RaisePropertyChanged("operatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public enum QueryOperator {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("=")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("!=")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<=")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(">=")]
        Item5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXLong : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
                this.RaisePropertyChanged("changed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
                this.RaisePropertyChanged("changedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
                this.RaisePropertyChanged("operatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXGLComponent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int glorderField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int glorder {
            get {
                return this.glorderField;
            }
            set {
                this.glorderField = value;
                this.RaisePropertyChanged("glorder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXGLAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vALUEField;
        
        private MXGLComponent[] gLCOMPField;
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VALUE {
            get {
                return this.vALUEField;
            }
            set {
                this.vALUEField = value;
                this.RaisePropertyChanged("VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GLCOMP", Order=1)]
        public MXGLComponent[] GLCOMP {
            get {
                return this.gLCOMPField;
            }
            set {
                this.gLCOMPField = value;
                this.RaisePropertyChanged("GLCOMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
                this.RaisePropertyChanged("changed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
                this.RaisePropertyChanged("changedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
                this.RaisePropertyChanged("operatorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool changedField;
        
        private bool changedFieldSpecified;
        
        private QueryOperator operatorField;
        
        private bool operatorFieldSpecified;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
                this.RaisePropertyChanged("changed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
                this.RaisePropertyChanged("changedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryOperator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
                this.RaisePropertyChanged("operatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SWWOSTATUS_OBJ2_WOSTATUS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public abstract partial class MXMBO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProcessingAction actionField;
        
        private bool actionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public enum ProcessingAction {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Change,
        
        /// <remarks/>
        Replace,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        AddChange,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXResponseCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] responseContentField;
        
        private string expressionLanguageField;
        
        public MXResponseCriteria() {
            this.expressionLanguageField = "XPath";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseContent", Order=0)]
        public string[] ResponseContent {
            get {
                return this.responseContentField;
            }
            set {
                this.responseContentField = value;
                this.RaisePropertyChanged("ResponseContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
                this.RaisePropertyChanged("expressionLanguage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXSender : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string majorversionField;
        
        private string minorversionField;
        
        private string buildField;
        
        private string dbbuildField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string majorversion {
            get {
                return this.majorversionField;
            }
            set {
                this.majorversionField = value;
                this.RaisePropertyChanged("majorversion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minorversion {
            get {
                return this.minorversionField;
            }
            set {
                this.minorversionField = value;
                this.RaisePropertyChanged("minorversion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
                this.RaisePropertyChanged("build");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dbbuild {
            get {
                return this.dbbuildField;
            }
            set {
                this.dbbuildField = value;
                this.RaisePropertyChanged("dbbuild");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXResponseHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXQueryHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXNotifyHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MXSender senderIDField;
        
        private System.DateTime creationDateTimeField;
        
        private string recipientIDField;
        
        private string messageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MXSender SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CreationDateTime {
            get {
                return this.creationDateTimeField;
            }
            set {
                this.creationDateTimeField = value;
                this.RaisePropertyChanged("CreationDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecipientID {
            get {
                return this.recipientIDField;
            }
            set {
                this.recipientIDField = value;
                this.RaisePropertyChanged("RecipientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXResponseHeader : MXHeader {
        
        private string operationField;
        
        private bool eventField;
        
        private bool eventFieldSpecified;
        
        private string rsStartField;
        
        private string rsCountField;
        
        private string rsTotalField;
        
        public MXResponseHeader() {
            this.operationField = "Response";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
                this.RaisePropertyChanged("event");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventSpecified {
            get {
                return this.eventFieldSpecified;
            }
            set {
                this.eventFieldSpecified = value;
                this.RaisePropertyChanged("eventSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsStart {
            get {
                return this.rsStartField;
            }
            set {
                this.rsStartField = value;
                this.RaisePropertyChanged("rsStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsCount {
            get {
                return this.rsCountField;
            }
            set {
                this.rsCountField = value;
                this.RaisePropertyChanged("rsCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsTotal {
            get {
                return this.rsTotalField;
            }
            set {
                this.rsTotalField = value;
                this.RaisePropertyChanged("rsTotal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXQueryHeader : MXHeader {
        
        private MXResponseCriteria responseCriteriaField;
        
        private string operationField;
        
        private bool uniqueResultField;
        
        private bool uniqueResultFieldSpecified;
        
        private string maxItemsField;
        
        private string rsStartField;
        
        public MXQueryHeader() {
            this.operationField = "Query";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MXResponseCriteria ResponseCriteria {
            get {
                return this.responseCriteriaField;
            }
            set {
                this.responseCriteriaField = value;
                this.RaisePropertyChanged("ResponseCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool uniqueResult {
            get {
                return this.uniqueResultField;
            }
            set {
                this.uniqueResultField = value;
                this.RaisePropertyChanged("uniqueResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uniqueResultSpecified {
            get {
                return this.uniqueResultFieldSpecified;
            }
            set {
                this.uniqueResultFieldSpecified = value;
                this.RaisePropertyChanged("uniqueResultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string maxItems {
            get {
                return this.maxItemsField;
            }
            set {
                this.maxItemsField = value;
                this.RaisePropertyChanged("maxItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rsStart {
            get {
                return this.rsStartField;
            }
            set {
                this.rsStartField = value;
                this.RaisePropertyChanged("rsStart");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXNotifyHeader : MXHeader {
        
        private string operationField;
        
        private bool eventField;
        
        private bool eventFieldSpecified;
        
        public MXNotifyHeader() {
            this.operationField = "Notify";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
                this.RaisePropertyChanged("event");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventSpecified {
            get {
                return this.eventFieldSpecified;
            }
            set {
                this.eventFieldSpecified = value;
                this.RaisePropertyChanged("eventSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXResponseInterface))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXQueryInterface))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MXNotifyInterface))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SWWOSTATUS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public abstract partial class MXInterfaceBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXResponseInterface : MXInterfaceBase {
        
        private MXResponseHeader headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MXResponseHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXQueryInterface : MXInterfaceBase {
        
        private MXQueryHeader headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MXQueryHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SWWOSTATUS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXNotifyInterface : MXInterfaceBase {
        
        private MXNotifyHeader headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MXNotifyHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mro.com/mx/integration")]
    public partial class MXDomain : MXString {
        
        private string maxvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxvalue {
            get {
                return this.maxvalueField;
            }
            set {
                this.maxvalueField = value;
                this.RaisePropertyChanged("maxvalue");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mro.com/mx/integration", Order=0)]
        public softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUS SWWOSTATUS;
        
        public processDocumentRequest() {
        }
        
        public processDocumentRequest(softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUS SWWOSTATUS) {
            this.SWWOSTATUS = SWWOSTATUS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processDocumentResponse {
        
        public processDocumentResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWWOSTATUSPortTypeChannel : softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWWOSTATUSPortTypeClient : System.ServiceModel.ClientBase<softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUSPortType>, softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUSPortType {
        
        public SWWOSTATUSPortTypeClient() {
        }
        
        public SWWOSTATUSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWWOSTATUSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWWOSTATUSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWWOSTATUSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        softWrench.sW4.mea_swWorkorderStatus.processDocumentResponse softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUSPortType.processDocument(softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest request) {
            return base.Channel.processDocument(request);
        }
        
        public void processDocument(softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUS SWWOSTATUS) {
            softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest inValue = new softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest();
            inValue.SWWOSTATUS = SWWOSTATUS;
            softWrench.sW4.mea_swWorkorderStatus.processDocumentResponse retVal = ((softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUSPortType)(this)).processDocument(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<softWrench.sW4.mea_swWorkorderStatus.processDocumentResponse> softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUSPortType.processDocumentAsync(softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest request) {
            return base.Channel.processDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<softWrench.sW4.mea_swWorkorderStatus.processDocumentResponse> processDocumentAsync(softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUS SWWOSTATUS) {
            softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest inValue = new softWrench.sW4.mea_swWorkorderStatus.processDocumentRequest();
            inValue.SWWOSTATUS = SWWOSTATUS;
            return ((softWrench.sW4.mea_swWorkorderStatus.SWWOSTATUSPortType)(this)).processDocumentAsync(inValue);
        }
    }
}
