

INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                            ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217928,'PAG1'      ,'Agincourt'  ,'8550 Camp Rock Road Lucerne Valley CA 92356','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PAG'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle  ,singlelineaddress                    ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217929,'PDS1'      ,'Antelope DSR1','42656 W. 90th St Lancaster CA 93536','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PDS1'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle  ,singlelineaddress                  ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217930,'PDS2'      ,'Antelope DSR2','44254 105th St Lancaster CA 93534','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PDS2'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle  ,singlelineaddress                  ,primarycontact ,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail   ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217931,'PNL1'      ,'AP North Lake','3601 W. Acacia Ave Hemet CA 92545','John Quinonez','4802399538'       ,'John.Quinonez@firstsolar.com','4802399538@txt.att.net','Jay Shaw'       ,'4803134693'          ,'Jay.Shaw@firstsolar.com','4803134693@vtext.com'   ,'PNL'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle          ,singlelineaddress                                   ,primarycontact ,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail   ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217932,'PBX1'      ,'Bixby 1-KTR Rochester','8599 Rochester Ave # 110 Rancho Cucamonga CA 91730','John Quinonez','4802399538'       ,'John.Quinonez@firstsolar.com','4802399538@txt.att.net','Jay Shaw'       ,'4803134693'          ,'Jay.Shaw@firstsolar.com','4803134693@vtext.com'   ,'PBX1'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle         ,singlelineaddress                     ,primarycontact,primarycontactphone,primarycontactemail          ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail        ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217934,'CFN1'      ,'CA Flats N - 130MWac','19855 E. Highway 41 Shandon CA 93451','Josh Tillery','8053699924'       ,'Josh.Tillery@firstsolar.com','8053699924@vtext.com','Nick Park'      ,'6618091440'          ,'Nicholas.Park@firstsolar.com','6618091440@vtext.com'   ,'CFN'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle         ,singlelineaddress,primarycontact,primarycontactphone,primarycontactemail          ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail        ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217935,'CFS1'      ,'CA Flats S - 150MWac',null             ,'Josh Tillery','8053699924'       ,'Josh.Tillery@firstsolar.com','8053699924@vtext.com','Nick Park'      ,'6618091440'          ,'Nicholas.Park@firstsolar.com','6618091440@vtext.com'   ,'CFN'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle      ,singlelineaddress,primarycontact ,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail   ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217937,'PBX2'      ,'Bixby 2-Mira Loma',null             ,'John Quinonez','4802399538'       ,'John.Quinonez@firstsolar.com','4802399538@txt.att.net','Jay Shaw'       ,'4803134693'          ,'Jay.Shaw@firstsolar.com','4803134693@vtext.com'   ,'PBX2'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle           ,singlelineaddress,primarycontact ,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail   ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217938,'PBX3'      ,'Bixby 3-Dupont Ontario',null             ,'John Quinonez','4802399538'       ,'John.Quinonez@firstsolar.com','4802399538@txt.att.net','Jay Shaw'       ,'4803134693'          ,'Jay.Shaw@firstsolar.com','4803134693@vtext.com'   ,'PBX3'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle     ,singlelineaddress                       ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217939,'PCA1'      ,'Central Antelope','95th St West Ave. H Lancaster CA 93536','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PCA'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle  ,singlelineaddress                      ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217940,'PDL1'      ,'Duke Longboat','25685 Community Blvd Barstow CA 92311','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PDL'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                    ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217941,'PLC1'      ,'Elevation C','9632 West Ave. G Lancaster CA 93536','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PLC'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                            ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217942,'PMR1'      ,'Marathon'   ,'8550 Camp Rock Road Lucerne Valley CA 92356','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PMR'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                      ,primarycontact ,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail   ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217943,'PMW1'      ,'Midway 1'   ,'6826 English Road Calipatria CA 92233','John Quinonez','4802399538'       ,'John.Quinonez@firstsolar.com','4802399538@txt.att.net','Jay Shaw'       ,'4803134693'          ,'Jay.Shaw@firstsolar.com','4803134693@vtext.com'   ,'PMW'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle          ,singlelineaddress                        ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217944,'PLR1'      ,'North Lancaster Ranch','44254 105TH St. West Lancaster CA 93534','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PLR'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle      ,singlelineaddress                       ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217945,'POV1'      ,'Owen''s Valley 11','1640 U.S. Highway 395 Olancha CA 93549','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'POV1'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle     ,singlelineaddress                       ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217946,'POV5'      ,'Owen''s Valley 5','1640 U.S. Highway 395 Olancha CA 93549','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'POV5'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                         ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217947,'PSV1'      ,'Solverde I' ,'Avenue L and 100th St Lancaster CA 93536','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PSV'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle ,singlelineaddress                   ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217949,'PSS1'      ,'Summer Solar','100th West & Hb Lancaster CA 93536','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PSS'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                    ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217950,'PWB1'      ,'WABSR'      ,'10302 West Ave G Lancaster CA 93536','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PWB'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                    ,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217951,'PWD1'      ,'WADR'       ,'10251 West Ave J Lancaster CA 93536','Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PWD'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                   ,primarycontact  ,primarycontactphone,primarycontactemail            ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail         ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217952,'PMV2'      ,'Mohave II'  ,'2486 Joy Lane Fort Mohave AZ 86426','Robert Sandner','6025711116'       ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com','Robert Sandner' ,'6025711116'          ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com'   ,'PMV2'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                        ,primarycontact  ,primarycontactphone,primarycontactemail            ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail         ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217953,'PPM1'      ,'PIMA'       ,'2501 North Flowing Road Tucson AZ 85701','Robert Sandner','6025711116'       ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com','Robert Sandner' ,'6025711116'          ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com'   ,'PPM'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                    ,primarycontact  ,primarycontactphone,primarycontactemail            ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail         ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217954,'PRR1'      ,'Red Rock'   ,'25990 East Camino Red Rock AZ 85145','Robert Sandner','6025711116'       ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com','Robert Sandner' ,'6025711116'          ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com'   ,'PPR'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                         ,primarycontact  ,primarycontactphone,primarycontactemail            ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail         ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217957,'PGV1'      ,'Grandview'  ,'325 S. Frederick Road Grandview ID 83624','Robert Sandner','6025711116'       ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com','Robert Sandner' ,'6025711116'          ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com'   ,'PGV'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                                  ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217958,'PCR1'      ,'Camp Ripley','15000 Minnesota Highway 115 Little Falls MN 56345','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PCR'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                     ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217959,'PDG1'      ,'Dodge'      ,'61801 240th Ave Mantorville MN 55955','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PDG'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                  ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217960,'PFR1'      ,'Farmington' ,'3398 225th St Farmington MN 55024','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PFR'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217961,'PFL1'      ,'Forest Lake',null             ,'Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PFL'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                           ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217962,'PHW1'      ,'HWY14'      ,'8257 Country Club Road West Byron MN 55920','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PHW'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                                   ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217963,'PPI1'      ,'Pine Island','50291 Highway 52 Blvd. Unit 1 Pine Island MN 55963','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PPI'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                          ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217964,'PWH1'      ,'Wabasha'    ,'1500 Hiawatha Drive East Wabasha MN 55981','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PWH'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                       ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217965,'PWR1'      ,'Webster'    ,'7380 40th St W Unit 1 Webster MN 55088','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'PWR'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle   ,singlelineaddress                        ,primarycontact  ,primarycontactphone,primarycontactemail            ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail         ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(217982,'PRM1'      ,'River Mountain','1299 Burkholder Blvd Henderson NV 89015','Robert Sandner','6025711116'       ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com','Robert Sandner' ,'6025711116'          ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com'   ,'PRM'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle ,singlelineaddress,primarycontact,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail      ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(218010,'PPR1'      ,'Portal Ridge',null             ,'Donny Sibley','6026634127'       ,'Donald.Sibley@firstsolar.com','6026634127@txt.att.net','Bruce Berry'    ,'6613417066'          ,'Bruce.Berry@firstsolar.com','6613417066@txt.att.net' ,'PPR'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                       ,primarycontact,primarycontactphone,primarycontactemail          ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail        ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(218013,'RSS1'      ,'Rancho Seco','14440 Twin Cities Road Herald CA 95638','Josh Tillery','8053699924'       ,'Josh.Tillery@firstsolar.com','8053699924@vtext.com','Nick Park'      ,'6618091440'          ,'Nicholas.Park@firstsolar.com','6618091440@vtext.com'   ,'RSS'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle   ,singlelineaddress                      ,primarycontact ,primarycontactphone,primarycontactemail           ,primarycontactsmsemail  ,escalationcontact,escalationcontactphone,escalationcontactemail   ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(261029,'MWS2'      ,'Midway Solar 2','7096 English Road Calipatria CA 92233','John Quinonez','4802399538'       ,'John.Quinonez@firstsolar.com','4802399538@txt.att.net','Jay Shaw'       ,'4803134693'          ,'Jay.Shaw@firstsolar.com','4803134693@vtext.com'   ,'MWS'          ,'1803'  ,'ORG6' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                   ,primarycontact  ,primarycontactphone,primarycontactemail            ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail         ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284777,'BRO1'      ,'Rosemount'  ,'2505 160th St E Rosemount MN 55068','Robert Sandner','6025711116'       ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com','Robert Sandner' ,'6025711116'          ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com'   ,'BRO'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                     ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284778,'BPA1'      ,'Paynesville','18982 293rd Ave Paynesville MN 56362','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BPA'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                       ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284779,'BSU1'      ,'Sunrise'    ,'36320 Kost Trail North Branch MN 55056','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BSU'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                      ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284780,'BCH1'      ,'Chisago'    ,'1152 Furuby Rd Taylors Falls MN 55084','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BCH'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                   ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284781,'BNO1'      ,'Northfield' ,'2300 North Ave Northfield MN 55057','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BNO'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                        ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284782,'BOR1'      ,'Orion'      ,'14008 Fruit Farm Rd St. Joseph MN 56374','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BOR'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                    ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284783,'BUR1'      ,'Ursa'       ,'1650 190th St W Farmington MN 55024','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BUR'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                  ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284784,'BMA2'      ,'Mapleton'   ,'12150 590th Ave Mapleton MN 56065','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BMA'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                    ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284785,'BMO2'      ,'Morgan'     ,'43781 County Road 3 Morgan MN 56266','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BMO'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                        ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284787,'BPE2'      ,'Pegasus'    ,'573 Central Ave. North Brooten MN 56316','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BPE'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                 ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284788,'BAR2'      ,'Aries'      ,'402 Church St Claremont MN 55924','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BAR'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                       ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284792,'BSP2'      ,'Spica'      ,'13833 195 Ave SE Lake Lillian MN 56253','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BSP'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress               ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284793,'BCE2'      ,'Centaurus'  ,'4085 Hwy 7 SE Maynard MN 56260','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BCE'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress               ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284794,'BAN2'      ,'Antlia'     ,'1637 41st St Edgerton MN 56128','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BAN2'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                    ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284795,'BGE2'      ,'Gemini'     ,'24299 Olinda Trail Scandia MN 55073','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BGE'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle,singlelineaddress                 ,primarycontact   ,primarycontactphone,primarycontactemail             ,primarycontactsmsemail,escalationcontact ,escalationcontactphone,escalationcontactemail           ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284800,'BVE2'      ,'Vega'       ,'19797 180th St Glenwood MN 56334','Ryan Schmiesing','3202937377'       ,'Ryan.Schmiesing@firstsolar.com','3202937377@vtext.com','Johnny Nicholson','4193660685'          ,'Johnny.Nicholson@firstsolar.com','4193660685@vtext.com'   ,'BVE'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
INSERT INTO GFED_SITE 
(gfedid,facilityname,facilitytitle  ,singlelineaddress,primarycontact  ,primarycontactphone,primarycontactemail            ,primarycontactsmsemail,escalationcontact,escalationcontactphone,escalationcontactemail         ,escalationcontactsmsemail,locationprefix,siteid,orgid,address,city,state,postalcode,country,sitecontact,sitecontactphone,supportphone,gpslatitude,gpslongitude,maintenaceprovider,wherehouseaddress) VALUES
(284806,'MHS1'      ,'Mountain Home',null             ,'Robert Sandner','6025711116'       ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com','Robert Sandner' ,'6025711116'          ,'Robert.Sandner@firstsolar.com','6025711116@vtext.com'   ,'MHS'          ,'1801'  ,'ORG4' ,null   ,null,null ,null      ,null   ,null       ,null            ,null        ,null       ,null        ,null              ,null             )
;
